[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module="natlinkcore"
author = "Joel Gould"
author-email = "joelg@alum.mit.edu"
maintainer = "Quintijn Hoogenboom"
maintainer-email = "q.hoogenboom@antenna.nl"
home-page = "https://qh.antenna.nl/unimacro/"
description-file = "README.md"

requires=[ 
		  "pywin32 >= 300",
		  "debugpy",
		  "pyenvutils",
		  "wxpython == 4.0.7; python_version>='3.8'",
		  "wxpython == 4.0.3; python_version<'3.7'"]
	  
		
classifiers=[	"Development Status :: 4 - Beta",
				"Topic :: Multimedia :: Sound/Audio :: Speech",
				"Topic :: Scientific/Engineering :: Human Machine Interfaces",
				]
				
requires-python = ">=3.8"
dist-name="natlink"
keywords="dragon,speech,dictation,dictation-toolobx,unimacro,natlink"

[tool.flit.scripts]
#commands that go in site-packages/scripts and end up in the system path
#note they currently don't work because MacroSystem/core and ConfigureNatlink 
#are not in the python path, so the import statements won't find the other modules in 
#the folder.

natlinkconfig_cli="natlinkcore.ConfigureNatlink.natlinkconfigfunctions:main"
natlinkconfig="natlinkcore.ConfigureNatlink.start_configurenatlink:main"


